# Site settings
title: Berlin Trash Talk
email: berlintrashtalk@posteo.de
description: > # this means to ignore newlines until "baseurl:"
  Sex, gossip and bad accents. Virgins in the eye of god.
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
